name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run unit tests
        run: |
          ./tests/run-tests.sh

      - name: Run unit tests with real storage
        run: |
          export repository_impl=pickle
          ./tests/run-tests.sh

      - name: Run unit tests with mongo
        run: |
          docker pull mongo:latest
          export repository_impl=mongo
          ./tests/run-tests.sh

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: LoveLetter
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: LoveLetter
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'love-letter'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2B1A5D895B6C4B299CB16E49C82CE0F5 }}