name: tests

on:
  push:
    branches:
      - feature/test_deploy_on_azure
  pull_request:
    branches:
      - master

permissions:
      id-token: write
      contents: read

env:
  IMAGE_NAME: "love-letter"
  DOCKERHUB_USERNAME: "eddy15201"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - uses: actions/setup-python@v4
#        with:
#          python-version: "3.10"
#
#      - name: Run unit tests
#        run: |
#          ./tests/run-tests.sh

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
